name: CI

on:
  push:
    branches: ['main', 'feature/settings']

jobs:
  frontendCI:
    name: Frontend CI Pipeline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Build shared
      working-directory: ./shared

      run: npm install && tsc && npm pack

    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run linter
      working-directory: ./frontend
      run: npm run lint

    - name: Build

      working-directory: ./frontend

      run: npm run build
    
  backendCI: 
    needs: frontendCI
    name: Backend CI Pipeline
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with: 
          bun-version: latest

      - name: Build shared
        working-directory: ./shared
        run: bun pm pack

      - name: Install dependencies
        working-directory: ./backend
        
        run: bun install

      - name: Run Linter
        working-directory: ./backend
        run: bun run lint
  